apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: helsearbeidsgiver
  name: hag-lps-api-client
  namespace: helsearbeidsgiver
spec:
  ingresses:
    - https://hag-lps-api-client.ekstern.dev.nav.no
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: "250m"
      memory: "768Mi"
    limits:
      memory: "1024Mi"
  secureLogs:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:authentication/systemregister.write"
        - name: "altinn:authentication/systemuser.request.write"
        - name: "nav:helse/im.read"

  accessPolicy:
    outbound:
      external:
        - host: "sykepenger-im-lps-api.ekstern.dev.nav.no"
        - host: "platform.tt02.altinn.no"

  envFrom:
    - secret: tigersys-maskinporten
