openapi: "3.1.0"
info:
  title: "Tigersys API"
  description: "Api for å registrere ny bedrift og hente systembruker token"
  version: "1.0.0"
paths:
  /registrer-ny-bedrift:
    post:
      description: ""
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                kundeOrgnr:
                  type: string
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Mangler 'kundeOrgnr' parameter"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RegistrerRespons"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /systembruker:
    post:
      description: "Henter systembruker token for en gitt orgnr"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                orgnr:
                  type: string
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Missing 'orgnr' parameter"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TokenResponseWrapper"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
components:
  schemas:
    RegistrerRespons:
      type: "object"
      properties:
        confirmUrl:
          type: "string"
    TokenResponse:
      type: "object"
      properties:
        accessToken:
          type: "string"
        tokenType:
          type: "string"
        expiresInSeconds:
          type: "integer"
          format: "int64"
        scope:
          type: "string"
      required:
        - "accessToken"
        - "tokenType"
        - "expiresInSeconds"
        - "scope"
    TokenResponseWrapper:
      type: "object"
      properties:
        tokenResponse:
          $ref: "#/components/schemas/TokenResponse"
      required:
        - "tokenResponse"