name: Build and Upload JAR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build JAR
        run: ./gradlew clean build

      - name: Make Executable JAR
        run: ./gradlew jar

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-executable
          path: build/libs/*.jar
          retention-days: 30
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
