name: Build and Upload JAR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build JAR
        run: ./gradlew clean build

      - name: Make Executable JAR
        run: ./gradlew jar

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-executable
          path: build/libs/*.jar
          retention-days: 30 # Retain for 30 days (adjust as needed)
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
